Update step_definition.py
1.51s$ mypy --ignore-missing-imports tests
utils/step_definition.py:45: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
Found 1 error in 1 file (checked 10 source files)
The command "mypy --ignore-missing-imports tests" exited with 1.